#! /bin/sh
# /etc/init.d/DIYPiper


# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting DIY Piper Daemon"
    sudo python /home/pi/DIY-Piper/runner.py &
    sudo python /home/pi/DIY-Piper/shutdown.py &
    ;;
  stop)
    echo "TODO: work out how to stop"
    ;;
  *)
    echo "Usage: /etc/init.d/DIYPiper {start|stop}"
    exit 1
    ;;
esac

exit 0
